server:
  port: 9093

spring:
  application:
    name: boot-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  activemq:
    broker-url: tcp://47.116.79.240:61616
    packages:
      trust-all: true
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
  redis:
    host: localhost
    port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


