server:
  port: 9056
spring:
  application:
    name: boot-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    api-b:
      path: /test/**
      serviceId: boot-web
