server:
  port: 9450
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/tangwind/kh83-springcloud.git
          search-paths: myConfig
          username: tangwind
          password: 711Tcc817
          force-pull: true
      label: master

